version: '2'
services:
    temperaturemonitoring-app:
        image: temperaturemonitoring
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://temperaturemonitoring-mysql:3306/temperaturemonitoring?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    temperaturemonitoring-mysql:
        extends:
            file: mysql.yml
            service: temperaturemonitoring-mysql
